steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/jarvis-telegram-bot:latest', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/jarvis-telegram-bot:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'jarvis-telegram-bot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/jarvis-telegram-bot:latest'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'WEBHOOK_URL=$_WEBHOOK_URL,AUDIO_PIPELINE_URL=$_AUDIO_PIPELINE_URL,INTELLIGENCE_SERVICE_URL=$_INTELLIGENCE_SERVICE_URL,ALLOWED_USER_IDS=$_ALLOWED_USER_IDS,GOOGLE_DRIVE_FOLDER_ID=$_GOOGLE_DRIVE_FOLDER_ID'
      - '--set-secrets'
      - 'TELEGRAM_BOT_TOKEN=TELEGRAM_BOT_TOKEN:latest,GOOGLE_TOKEN_JSON=google-token-json:latest'

images:
  - 'gcr.io/$PROJECT_ID/jarvis-telegram-bot:latest'
